### ISSUE TITLE
hfst-ospell-cg should accept cg stream as input

### ISSUE THREAD

**Issue by snomos** [unhammer/hfst-ospell-cg#1]
Consider this pipeine:

```
$ echo "Nu go mii diehttit de lea guovddáš eiseváldit, SND čađa, vuoruhan doarjaga fatnasiidda mat leat stuorát go 15 mehtar." | hfst-tokenise --giella-cg tokeniser-gramcheck-gt-desc.pmhfst | vislcg3 -g valency.bin | vislcg3 -g mwe-dis.bin | cg-mwesplit | hfst-ospell-cg -a se.zhfst | l
```

As it is now, `hfst-ospell-cg` will take every single line as input, and make suggestions based on it, which in this context makes no sense. Instead there should be an option to say that the input is a CG stream, which would make it so that it only considers the actual input word forms, and skip everything else.

In addition, there should be an option to only spell-check word forms unrecognised by the earlier processing steps, ie lines with a question mark analysis.

**Comment by unhammer** [comment]
hfst-ospell-cg doesn't make any sense it that context, no. See [divvun-cgspell](https://github.com/divvun/divvun-gramcheck/commit/74ec73a12ba9ce4ccf9e5f1ec265e41e3808ddc5) :-)
